### ISSUE TITLE
اقتراح تعديل طريقة تضمين C++

### ISSUE THREAD

**Issue by waseeld** [alifcommunity/compiler#1]
مرحبا ..
اعاني من بعض المشاكل مع الوسم **_س_**  المسؤول عن تضمين اكواد C++

### المشكلة
وسم _س_ في لغة ألف حاليا يجب فتحه واغلاقه في نفس السطر مثال :

`_س_  أكواد غريبة ههه   _س_
`

ولا يجوز :

 ```
_س_ 

أكواد غريبة ايضا ههه

 _س_
```

**Comment by me00001** [comment]
جرب الشفرة التالية هي تعمل معي ثم أخبرني ماهو الخطأ ان وجد 
```
#ألف

دالة عدد ثنائي (عدد أ )
		_س_
			int a , b = 0 , c , k = 1 ;
			a = @أ@ ;
			while(a >= 1)
				{ 
				c = a % 2 ;
				if( c == 1)
					{ b = b + k ;
					 }
				a = a / 2 ;
				k = k * 10 ;
				}
			@أ@ = b ;
		_س_
	إرجاع أ
نهاية دالة
نافذة رئيسية 
	دالة رئيسية 
	
	عدد تحويل_ثنائي = ثنائي(31)
	رسالة(تحويل_ثنائي) 'الناتج 11111

	نهاية دالة 
نهاية نافذة 
```

**Comment by waseeld** [comment]
اوه فعلا شكرا لك @sulimanp 
بعد أن قرئت كودك ادركت الخطأ الذي وقعت فيه
