### ISSUE TITLE
linking

### ISSUE THREAD

**Issue by mohamedke** [alifcommunity/compiler#10]
<div dir=rtl>

مكتبة webui تستخدم مكتبة boost الديناميكية
بينما لغة ألف تستخدم تستخدم مكتبة boost الساكنة وهذا ما يحدث خطأ أثناء الربط
هذه نتائج الأمر بالنسبة للمثال helloworld الموجود ضمن مكتبة webui في نخسة سابقة

<div dir=ltr>

```
ldd helloworld 
	linux-vdso.so.1 (0x00007ffe29779000)
	libboost_filesystem.so.1.71.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0 (0x00007fafd95d2000)_**
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fafd93f1000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fafd93d6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fafd93b3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fafd91c1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fafd9072000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fafd975e000)
```

</div>

أما لغة ألف فهي تستعمل libbosst_filesystem

</div>

**Comment by hassandraga** [comment]
بما أنا أمثلة تستعمل مكتبة بوست واحدة وهي filesystem قررت ضمها للبرنامج، أي ساكنة.

جرب نسخة 1.0.5
ونظر هل تعمل WebUI بشكل جيد
أما ألف فذاك نحله لاحقا إن شاء الله

**Comment by hassandraga** [comment]
آسف، ضننت هته صفحة مكتبة WebUI ! 
دع هذا المشكل مفتوح لغاية حله لاحقا في المرحلة الثانية

**Comment by hassandraga** [comment]
<div dir="rtl">
ثم الحل نسخة 3.0.30

**Comment by me00001** [comment]
<div dir="rtl"> 

> ثم الحل نسخة 3.0.30

ألف الأن تستخدم مكتبة boost الديناميكية ؟ 
في جنو/لينكس

**Comment by hassandraga** [comment]
<div dir="rtl">
نعم
