### ISSUE TITLE
building alif compiler at windows

### ISSUE THREAD

**Issue by mohamedke** [alifcommunity/compiler#13]
<div dir=rtl>

عند محاولة بناء مترجم ألف على وندوز gcc يظهر هذا الخطأ، وهو فقدان مكتبة iconv

</div>

```
[ 50%] Building CXX object Alif/CMakeFiles/alif.dir/alif.cpp.obj
[100%] Linking CXX executable C:\Alif3\alif.exe
C:/Alif3/gcc/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -liconv
C:/Alif3/gcc/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -liconv
collect2.exe: error: ld returned 1 exit status
Alif\CMakeFiles\alif.dir\build.make:110: recipe for target 'C:/Alif3/alif.exe' failed
mingw32-make[2]: *** [C:/Alif3/alif.exe] Error 1
CMakeFiles\Makefile2:111: recipe for target 'Alif/CMakeFiles/alif.dir/all' failed
mingw32-make[1]: *** [Alif/CMakeFiles/alif.dir/all] Error 2
Makefile:101: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا ، Alif 3.0.20 غير متوافق مع TDM-GCC ، تحتاج إلى تثبيت MinGW-64 ، سيتم إصلاح هذا في الإصدار التالي.

**Comment by mohamedke** [comment]
تلك مشكلة أخ حسن.
وتلك المشكلة تحدث في كل من tdm gcc و mingw gcc لا أدري لماذا
لكنها لا تحدث في المترجم المرفق مع ألف
بينما هاته المشكلة فهي بسبب فقدان مكتبة iconv

**Comment by hassandraga** [comment]
<div dir="rtl">
ثم التصحيح في نسخة 3.0.21، المرجو المراجعة والتدقيق

شكرا على التبليغ

**Comment by me00001** [comment]
الخطأ غير موجود

ألف 3.0.21 
MinGW

**Comment by mohamedke** [comment]
تم إصلاح المشكل والحمد لله
شكرا ، جزاك الله خيرا

**Comment by mohamedke** [comment]
تم إصلاح المشكل والحمد لله
شكرا ، جزاك الله خيرا

**Comment by mohamedke** [comment]
تم حل المشكل
شكرا لك

**Comment by mohamedke** [comment]
تم حل المشكل
شكرا لك
