### ISSUE TITLE
Alif 3.0.21 - Linux Compatibility

### ISSUE THREAD

**Issue by hassandraga** [alifcommunity/compiler#16]
<div dir="rtl">
يستخدم مترجم ألف مكتبة Boost.Nowide للتعامل مع اسم ملف UTF8 عبر الأنظمة، 

تمت إضافة هذه المكتبة رسميًا إلى الإصدار 1.73 من Boost. 
تكمن المشكلة في أن غالبية توزيعات Linux لا تزال تقدم إصدار Boost 1.71 ، والذي لا يشمل مكتبة Boost.Nowide. 
نحتاج إلى البحث عن طريقة سهلة لتثبيت Boost 1.73 على Linux.

**Comment by hassandraga** [comment]
Testing (_untrusted_): https://launchpad.net/~mhier/+archive/ubuntu/libboost-latest

**Comment by assawalhy** [comment]
ذا هو الإصدار الذي لدي على لينوكس آرش

![image](https://user-images.githubusercontent.com/42011920/122964503-dd758400-d376-11eb-8828-994a14d45f32.png)

**Comment by assawalhy** [comment]
نجحت الترجم الحمد لله

![image](https://user-images.githubusercontent.com/42011920/122964577-ef572700-d376-11eb-876d-0749fd25e54b.png)

**Comment by me00001** [comment]
### هذا ممكن

**الخطوات**
```
wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz

tar -xzf boost_1_76_0.tar.gz

cd boost_1_76_0

./bootstrap.sh

./b2 --layout=system address-model=64 --stagedir=stage/x64/Release variant=release link=static runtime-link=shared warnings=off --with-filesystem --with-program_options --with-system --with-locale --with-date_time --with-regex --with-nowide

```

**الخرج يشبه**
```
The Boost C++ Libraries were successfully built!

The following directory should be added to compiler include paths:

    /home/suliman/boost/boost_1_76_0

The following directory should be added to linker library paths:

    /home/suliman/boost/boost_1_76_0/stage/x64/Release/lib

```
----
**عند بناء ألف اعتمد على الخرج السابق لتنفيذ التالي**

```
cmake .. . -D BOOST_ROOT=/home/suliman/boost/boost_1_76_0 -D BOOST_LIBRARYDIR=/home/suliman/boost/boost_1_76_0/stage/x64/Release/lib
```

**Comment by me00001** [comment]
ويمكن أن تضيف
`./b2 install --prefix=/usr/local --layout=system address-model=64 --stagedir=stage/x64/Release variant=release link=static runtime-link=shared warnings=off --with-filesystem --with-program_options --with-system --with-locale --with-date_time --with-regex --with-nowide` 
لتثبيت المكتبة في النظام لكن تحتاج الى
 sudo

**Comment by waseeld** [comment]
<div dir="rtl">
@me00001 
شكرا لك سليمان هذا يعمل معي بنجاح لكن يجب تصدير boost في البيئة

<br/>
<br/>
ملاحظة :
تأكد من تصفية مجلد build قبل أعادة البناء

</div>

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا أخ سليمان، غدا سأنتقل للينكس وسأضيف هذا الحل

**Comment by hassandraga** [comment]
https://github.com/alifcommunity/compiler/blob/main/README.md
