### ISSUE TITLE
المسارات المطلقة

### ISSUE THREAD

**Issue by me00001** [alifcommunity/compiler#17]
<div dir="rtl">

لم يعمل البناء حتى أزلتهم 

ونفس الأمر لمسارات المترجم
</div>

https://github.com/alifcommunity/compiler/blob/2e46c84157ad571b1b39e55b5c3e2a917611f466/CMakeLists.txt#L8-L17

https://github.com/alifcommunity/compiler/blob/2e46c84157ad571b1b39e55b5c3e2a917611f466/CMakeLists.txt#L23-L39

https://github.com/alifcommunity/compiler/blob/2e46c84157ad571b1b39e55b5c3e2a917611f466/src/CMakeLists.txt#L42-L45

<div dir="rtl">

هل توجد مشكلة إذا ازلتهم ؟ 
</div>

**Comment by me00001** [comment]
**MinGW**
https://github.com/me00001/compiler/runs/2906437077?check_suite_focus=true

**MSVC**
https://github.com/me00001/compiler/runs/2906437218?check_suite_focus=true

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا على التبليغ

بعض المستخدمين سيحتاجونها، لدى أضفت هذا السطر في النسخة 3.0.22 لحل المشكل
```
if (WIN32)
    if(EXISTS "C:/Alif3/")
        ...
    endif()
endif()
```

**Comment by me00001** [comment]
شكرًأ انحلت المشكلة
