### ISSUE TITLE
no build files, no guides on how to build the compiler

### ISSUE THREAD

**Issue by aboualiaa** [alifcommunity/compiler#2]

**Comment by hassandraga** [comment]
Thank you for your commits, we are actually writing Alif 3 algorithmes, and completely a new GUI library from scratch, that's use Web browsers as UI, called WebUI. We will push the first version of Alif 3 in a couple of weeks.

But I will include your make file script in Alif 3.

Cheers,

**Comment by aboualiaa** [comment]
Thank you for your reply.. why isn't the active development on github? I would love to contribute..

**Comment by hassandraga** [comment]
There no new code yet for the compiler, while the WebUI is almost done, I will create a new rep tonight and add it.

**Comment by hassandraga** [comment]
@aboualiaa Hi, please give me your email/telegram/twitter.. if possible, I have something to say. Thank you.

**Comment by aboualiaa** [comment]
@hassandraga feel free to contact me on twitter: @aboualiaa

**Comment by hassandraga** [comment]
I can't PM you on twitter, please accept request or PM me @dragahassan
