### ISSUE TITLE
إمكانية ربط مكتبات بعينها أثناء عملية الترجمة وانتاج الملف التنفيذي الثنائي

### ISSUE THREAD

**Issue by assawalhy** [alifcommunity/compiler#21]
<div dir=rtl>

عن طريق الماكرو

#أضف_في_ترجمة <span dir=ltr>"-mbig-obj"</span>
#أضف_في_التجميع <span dir=ltr>"-lboost_filesystem -lwebsocket"</span>

عن طريق سطر الأوامر

</div>

```
alif test.alif --o test.exe --clib webui --clib boost_filesystem
```

_Originally posted by @hassandraga in https://github.com/alifcommunity/compiler/issues/8#issuecomment-803497355_

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا على التبليغ

سيتم إضافة هته الميزة في النسخة القادمة إن شاء الله

**Comment by hassandraga** [comment]
<div dir="rtl">
ثم الحل نسخة 3.0.30

```
#إذا ماك أضف_ترجمة " "
#إذا ماك أضف_تجميع " "

#إذا ويندوز أضف_ترجمة "  "
#إذا ويندوز أضف_تجميع "  "

#إذا لينكس أضف_ترجمة "  "
#إذا لينكس أضف_تجميع "  "
```

`--clib boost_filesystem`
