### ISSUE TITLE
تثبيت مخصص في مسار مختلف

### ISSUE THREAD

**Issue by me00001** [alifcommunity/compiler#23]
مالمعوقات لعدم عمل هذا ؟

برأيي نحتاج الى تثبيت ألف في أي مكان, اي نقوم بتفعيل ميزة 
`cmake -DCMAKE_INSTALL_PREFIX=<path/to/install/alif>`
حتى يمكننا استخدامه في أي مكان بدون تثبيته مباشرة في النظام 

مثال 
```

$ cmake .. . -DCMAKE_INSTALL_PREFIX=$(pwd)/opt

$ make        
[ 50%] Building CXX object Alif/CMakeFiles/alif.dir/alif.cpp.o
[100%] Linking CXX executable alif
[100%] Built target alif

$ make install
Consolidate compiler generated dependencies of target alif
[100%] Built target alif
Install the project...
-- Install configuration: ""
-- Installing: /home/suliman/git/compiler/build/opt/bin/alif
-- Set runtime path of "/home/suliman/git/compiler/build/opt/bin/alif" to ""
-- Installing: /home/suliman/git/compiler/build/opt/lib/aliflib
-- Installing: /home/suliman/git/compiler/build/opt/lib/aliflib/alif.ico
-- Installing: /home/suliman/git/compiler/build/opt/lib/aliflib/alifcore.cc
-- Installing: /home/suliman/git/compiler/build/opt/lib/aliflib/alifstandardlib.alif
-- Installing: /home/suliman/git/compiler/build/opt/lib/aliflib/libwebui.a
-- Installing: /home/suliman/git/compiler/build/opt/lib/aliflib/webui.hpp
-- Installing: /home/suliman/git/compiler/build/opt/lib/aliflib/الواجهة.alif

$ cp ../examples/hello.alif .       
          
$ ./opt/bin/alif hello.alif
[!] Error
The core file is missing: [/usr/local/lib/aliflib/alifcore.cc]
Please re-install Alif Compiler, or download the latest version from http://www.aliflang.org

```

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا على التبليغ

سيتم إضافة هته الميزة في النسخة القادمة إن شاء الله

**Comment by hassandraga** [comment]
<div dir="rtl">
بعد البحث، تبين أن هدا غير ممكن في لينكس، بينما ممكنفي ويندوز.

**ويندوز:** 
جعلت ألف يبحث عن مجلد `aliflib` إنطلاقا مكانه، وهدا عاد لأن جميع مجلدات توجد في مكان واحد.
**لينكس:**
كل مجلد إلا وفي مكان مختلف، وفكرة ستخدام البحث إنطلاقا من مكان ألف غير منصوح بها، لدى الحل اللذي أراه هو إضافة أمر تخبر مترجم ألف عن مكان المجلدات

ما رآيك ؟
</div>

`--aliflib-path home/suliman/git/compiler/build/opt/lib/aliflib`

**Comment by hassandraga** [comment]
<div dir=rtl>
حاليا أقترح أن نستخدم غيت هاب فقط لتحديد شكل اللغة، مثلا في الشرط، هل نستخدم 

`إذا أ = ب` أو `إذا أ == ب`
فإذا اتفقنا نقوم بإافتها للمترجم، ثم نوتقها في الموقف كمرجع رئيسي للغة

**Comment by me00001** [comment]
<div dir="rtl">

> بعد البحث، تبين أن هدا غير ممكن في لينكس، بينما ممكنفي ويندوز.
> 
> **ويندوز:**
> جعلت ألف يبحث عن مجلد `aliflib` إنطلاقا مكانه، وهدا عاد لأن جميع مجلدات توجد في مكان واحد.
> **لينكس:**
> كل مجلد إلا وفي مكان مختلف، وفكرة ستخدام البحث إنطلاقا من مكان ألف غير منصوح بها، لدى الحل اللذي أراه هو إضافة أمر تخبر مترجم ألف عن مكان المجلدات
> 
> ما رآيك ؟
> 
> `--aliflib-path home/suliman/git/compiler/build/opt/lib/aliflib`

لا أتفق
سوف اذكر المزيد من التفاصيل في يوم أخر

**Comment by me00001** [comment]
<div dir="rtl">

>  جعلت ألف يبحث عن مجلد `aliflib` إنطلاقا مكانه، وهدا عاد لأن جميع مجلدات توجد في مكان واحد.

أقترح ان يبحث المترجم اولًا من اي مسار تم تشغيله ؟ 
في حال تم تثبيت المترجم بـ 
<div dir="ltr"> 

`-DCMAKE_INSTALL_PREFIX=/opt/Alif`
<div dir="rtl">
يقوم المترجم بالبحث من أي مسار تم تشغيله ؟ ثم يعود مجلد واحدد فقط للخلف ثم يجد هذي الشجرة 
<div dir="ltr">

```
tree /opt/Alif/
├── bin
│   └── alif
└── lib
    └── aliflib
```
<div dir="rtl">
ويعتبر هذا المجلد نقطة البداية  (المسار المطلق)

**مثال:** شغلت المترجم بالأمر
<div dir="ltr">

`/opt/Alif/bin/alif`
<div dir="rtl">
سيعلم المترجم بأنه تم تشغيله من المسار 
<div dir="ltr">

`/opt/Alif/bin`
<div dir="rtl">
لذا سيعود مجلد واحد للخلف
<div dir="ltr">

`/opt/Alif/`
<div dir="rtl">
وسيجد مجلد aliflib في 
<div dir="ltr">

`/opt/Alif/lib/aliflib`
<div dir="rtl">
ما رأيك ؟

**Comment by hassandraga** [comment]
<div dir="rtl">

فهمت، علينا فقط التيقن أن هده الطريقة ستعمل في جميع توزيعات لينكس

**Comment by me00001** [comment]
<div dir="rtl">

تم في https://github.com/alifcommunity/compiler/pull/42
