### ISSUE TITLE
تشغيل أكواد جافاسكريبت

### ISSUE THREAD

**Issue by mohamedke** [alifcommunity/compiler#24]
<div dir=rtl>

عند كتابة أي شيء سواء كلمات او فراغ داخل

```
_ج_ alert("hello"); _ج_
```

يظهر خطأ مثل التالي:

```
السطر		: 4
 الخطأ		: أمر غير معروف : ' alert("hello"); ' 
```

**Comment by assawalhy** [comment]
<div dir=rtl>

أرجو توفير بعض المعلومات أكثر، لو تضيف الشيفرة كاملة، وإصدار مترجم ألف.

</div>

**Comment by mohamedke** [comment]
<div dir=rtl>

شكرا على التنبيه
الإصدار ألف 3.0.21
النظام وندوز7، 64 بت
الشفرة هاهي
```

#ألف
#مكتبة "الواجهة"
#نص ص "win.html"
دالة رسالة(نص نصية)
	_ج_alert("hello");_ج_
نهاية دالة

دالة رئيسية 
		كائن ن = الواجهة (ص)
		ن : إظهار ()
		ن : إنتظار ()

نهاية دالة 

```

**Comment by mohamedke** [comment]
شكرا على التنبيه
الإصدار ألف 3.0.21
النظام وندوز7، 64 بت
الشفرة هاهي
```

#ألف
#مكتبة "الواجهة"
#نص ص "win.html"
دالة رسالة(نص نصية)
	_ج_alert("hello");_ج_
نهاية دالة

دالة رئيسية 
		كائن ن = الواجهة (ص)
		ن : إظهار ()
		ن : إنتظار ()

نهاية دالة 

```

**Comment by mohamedke** [comment]
شكرا على التنبيه
الإصدار ألف 3.0.21
النظام وندوز7، 64 بت
الشفرة هاهي
```

#ألف
#مكتبة "الواجهة"
#نص ص "win.html"
دالة رسالة(نص نصية)
	_ج_alert("hello");_ج_
نهاية دالة

دالة رئيسية 
		كائن ن = الواجهة (ص)
		ن : إظهار ()
		ن : إنتظار ()

نهاية دالة 

```

**Comment by me00001** [comment]
<div dir="rtl">
اعتقد لأن _ج_ لم تتوفر بعد في الواجهة الجديدة في ألف ٣ 

عكس ألف ٢ الميزة متوفرة مع الواجهة القديمة

**Comment by hassandraga** [comment]
<div dir="rtl">
ألف نسخة 1 و 2 كانت تدعم الواجهة بشكل مدمج مع اللغة لدى بإمكان ستخدام _ج_


الآن ألف 3 تتجه نحو إستقلالية أكثر، وكل الميزات ستوفرها المكتبات بدلا من اللغة نفسها، وهدا ماهو سائر في كل لغات العالمية

لتفيذ جافاسكريبت يمكنك ستخدام مكتبة ويب يو آي

```
#ألف
#مكتبة "الواجهة"
نص النتيجة = نافذتي : جافاسكريبت ( " alert(\"Salam!\"); " )
```

**Comment by mohamedke** [comment]
شكرا سأجربها وأعطي النتائج

**Comment by MuhammadSawalhy** [comment]
![image](https://user-images.githubusercontent.com/42011920/123522522-43327a80-d6ad-11eb-92fb-bf1e5ddd7455.png)

**Comment by assawalhy** [comment]
<div dir=rtl>

## المحاولة الأولى

### الكود

```
#ألف
#مكتبة "الواجهة"
نص النتيجة = نافذتي : جافاسكريبت ( " alert(\"Salam!\"); " )

دالة رئيسية
	اطبع(النتيجة)
نهاية دالة 
```

### الخطأ

```
الخطأ     : أمر غير معروف ' نافذتي ', كان من المتوقع أن يكون إسم مجال
```

## المحاولة الثانية

### الكود

```
#ألف
#مكتبة "الواجهة"
#نص ص "win.html"

دالة رئيسية 
		كائن ن = الواجهة (ص)
		نص النتيجة = ن : جافاسكريبت ( " alert(\"Salam!\"); " )
نهاية دالة 
```

### الخطأ

```
الخطأ     : الصنف ' الواجهة ' ليس فيه أي منتمي معرف باسم ' جافاسكريبت ' 
```

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا على التبليغ

السبب هو أن آخر نسخ مكتبات ألف تأتي مع برنامج الثتبت، ربما علينا دمجها هنا كذالك

**Comment by mohamedke** [comment]
شكرا أخ حسن.
تم حل المشكل ولله الحمد في النسخة الأخيرة

**Comment by assawalhy** [comment]
<div dir=rtl>

> شكرا أخ حسن.
> تم حل المشكل ولله الحمد في النسخة الأخيرة

أرسل لي الكود الذي يعمل

**Comment by mohamedke** [comment]
هل قمت بتحميل آخر نسخة من الموقع الرسمي؟
هذه هي الشيفرة التي تعمل
``` 
#ألف

#مكتبة "الواجهة"


#نص شيفرة_إتش_تي_إم_إل "ui.html"
كائن نافذتي = الواجهة (شيفرة_إتش_تي_إم_إل)


دالة نافذتي_حدث
	اطبع("Click!" + سطر)

نهاية دالة 


دالة رئيسية 

		نافذتي : ربط ( "MyButton1" ، نافذتي_حدث )
		نافذتي : إظهار ()

		اطبع ("Please wait 1 second.. \n")
		نم (1000)

		اطبع ("Please wait another one!.. \n")
		نم (1000)

		اطبع ("Run JavaScript.. \n")
		نص النتيجة = نافذتي : جافاسكريبت ( " document.getElementById(\"تجربة\").innerHTML = \"مرحبا من ألف !\"; " )

		نافذتي : إنتظار ()

نهاية دالة 
```

**Comment by hassandraga** [comment]
<div dir="rtl">
ثم الحل نسخة 3.0.30
