### ISSUE TITLE
تشنج الجهاز وقتل العملية تلقائيا

### ISSUE THREAD

**Issue by assawalhy** [alifcommunity/compiler#25]
<div dir=rtl>

عند محاولة ترجمة الكود التالي يتشنج الجهاز عندي وأقد القدر على تحريك الفأرة، وأذهب لأحد ال tty عن طريق <span dir=ltr><kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>F1</kbd></span> ولكن لا يظهر لي إدخال اسم المستخدم وكلمه السر، يظل متشنجا، إلى أن يقوم نظام التشغيل عندي بقتل العملية وإرسال إشار KILL لها.

```
نظام التشغيل: آرش لينوكس
نواة النظام: 5.12.12-arch1-1
إصدار مترجم ألف: v3.0.21
```

```

#ألف
دالة رسالة(نص نصية)
	_ج_alert("hello");_ج_
نهاية دالة
#مكتبة "الواجهة"
#نص ص "win.html"
صنف الزر
	عدد حقيقي
	دالة بناء ()
		اطبع( "build" + سطر )
    نهاية دالة
	دالة زر1()
		اطبع("click")
	نهاية دالة
نهاية صنف
دالة رئيسية 
		كائن زر2 = الزر()
		كائن ن = الواجهة (ص)
		ن : إظهار ()
		ن : إنتظار ()

نهاية دالة 

```

![image](https://user-images.githubusercontent.com/42011920/123402933-cb266080-d597-11eb-9ead-f619602d5b92.png)

</div>

**Comment by me00001** [comment]
مرتبط بـ https://github.com/alifcommunity/compiler/issues/7

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا على التبليغ

ثم إصلاح العلة في النسخة 3.0.22
