### ISSUE TITLE
الأتمتة

### ISSUE THREAD

**Issue by hassandraga** [alifcommunity/compiler#26]
<div dir=rtl>
@me00001 

أخ سليمان، لقد ثم التخلي عن مترجم مايكروسوفت و ستبداله ب MinGW64
هل تستطيغ تغيير الأتمتة لتستعمل MinGW64 بدلا من مترجم مايكروسوفت؟
هذا قد يساعدك 
https://github.com/marketplace/actions/install-mingw

**Comment by me00001** [comment]
شكرًا
مدعوم بالفعل
