### ISSUE TITLE
لا تظهر أي نوافذ

### ISSUE THREAD

**Issue by me00001** [alifcommunity/compiler#29]
<div dir=rtl>

فعلا نجحت الترجمة، لكن عند محاولة التشغيل هذا ما يحدث، ولا تظهر أي نوافذ

![image](https://user-images.githubusercontent.com/42011920/123605629-927ec500-d7eb-11eb-96d2-d2f2d73b509c.png)

_Originally posted by @MuhammadSawalhy in https://github.com/alifcommunity/compiler/issues/8#issuecomment-869488290_

**Comment by hassandraga** [comment]
WebUI check if Firefox is installed on your system using this command: 
`firefox -v >>/dev/null 2>>/dev/null`

If yes, Then WebUI create a new Firefox profile: 
`sh -c " firefox -CreateProfile "WebUI /var/tmp/WebUIFirefoxProfile" >>/dev/null 2>>/dev/null"`

If yes, Then WebUI run Firefox: 
`sh -c " firefox -P WebUI -private -no-remote -new-instance http://google.com >>/dev/null 2>>/dev/null"`

Can you please run those commands manually and see if it's work?
Can you please also provide your OS info?

**Comment by assawalhy** [comment]
<div dir=rtl>

توجد مشكلة أيضا في بناء webui، وأظن أن هذا هو السبب، عليا اختبار webui أولا

https://github.com/alifcommunity/webui/issues/15

</div>

**Comment by assawalhy** [comment]
> Can you please run those commands manually and see if it's work?
> Can you please also provide your OS info?

<div dir=rtl>

اشتغلت

</div>

~~~
OS: Arch Linux x86_64
Kernel: 5.12.12-arch1-1 
> firefox -v
Mozilla Firefox 89.0.1
~~~

**Comment by hassandraga** [comment]
Moved to https://github.com/alifcommunity/webui/issues/16

**Comment by hassandraga** [comment]
<div dir=rtl>

في مستودع WebUI ، أفضل التحدث باللغة الإنجليزية لأن WebUI هو مشروع عام دولي

**Comment by assawalhy** [comment]
<div dir=rtl>

اشتغلت هذه الأوامر لكن لا تزال المشكلة عند تشغيل أمثلة ألف التي تستخدم مكتبة الواجة

</div>


```
/var/tmp/WebUIFirefoxProfile" >>/dev/null 2>>/dev/null": line 1: firefox -CreateProfile WebUI: command not found
Please wait 1 second.. 
Please wait another one!.. 
Run JavaScript..
```

**Comment by assawalhy** [comment]
<div dir=rtl>

> في مستودع WebUI ، أفضل التحدث باللغة الإنجليزية لأن WebUI هو مشروع عام دولي


واللغة العربية جديرة بهذا ونريد الخروج بها للعالم، كما أنه من يريد التحدث من الغرب بلغته لا مشكلة.

**Comment by hassandraga** [comment]
<div dir=rtl>

> اشتغلت هذه الأوامر لكن لا تزال المشكلة عند تشغيل أمثلة ألف التي تستخدم مكتبة الواجة
> 
> ```
> /var/tmp/WebUIFirefoxProfile" >>/dev/null 2>>/dev/null": line 1: firefox -CreateProfile WebUI: command not found
> Please wait 1 second.. 
> Please wait another one!.. 
> Run JavaScript..
> ```

أقفلت هذا الخطأ لأن لاعلاقة لمترجم ألف به
هذا المشكل هو من مكتبة WebUI

**Comment by hassandraga** [comment]
<div dir=rtl>

> > في مستودع WebUI ، أفضل التحدث باللغة الإنجليزية لأن WebUI هو مشروع عام دولي
> 
> واللغة العربية جديرة بهذا ونريد الخروج بها للعالم، كما أنه من يريد التحدث من الغرب بلغته لا مشكلة.

أتفق معك، لكن الحكمة تفرض نفسها، فعلينا أن نرى الأمور بعقلانية وليس بحساسية. علينا مخاطبة العالم بلغته لكي نعرف مشاريعنا العربية.
فهذا رأي والله أعلم.

أنا لن افرض لغة معينة على أحد، فقط أشرت لماذا أستعمل الإنجليزية في مشاكل المتعلقة بمكتبة WebUI

**Comment by hassandraga** [comment]
<div dir=rtl>

@me00001 
شكرا لك على خريطة تطوير اللغة

**Comment by me00001** [comment]
> @me00001
> شكرا لك على خريطة تطوير اللغة

<div dir="rtl"> 
الخريطة من تأسيس @MuhammadSawalhy 
جزاه الله خيرا

**Comment by hassandraga** [comment]
<div dir=rtl>

@MuhammadSawalhy 
آه، لم أكن اعلم، شكرا جزيلا وجعله الله في ميزان حسناتك
أحب الأمور المنضمة، تظهر اننا في الطريق الصحيح
