### ISSUE TITLE
تاخر الطباعة عند كتابة الدالة اطبع

### ISSUE THREAD

**Issue by mohamedke** [alifcommunity/compiler#30]
عند استدعاء الدالة "اطبع" لايتم الطباعة في ذلك الوقت إلا إذا وجد معها سطر جديد
وإذا لم يكن هناك سطر جديد لا تتم الطباعة حتى توجد كلمة "سطر" او
"\n"
كمثال
```

#ألف

#مكتبة "الواجهة"


#نص شيفرة_إتش_تي_إم_إل "ui.html"
كائن نافذتي = الواجهة (شيفرة_إتش_تي_إم_إل)

نص إلتقاط

دالة نافذتي_حدث
	اطبع("Click!")
نهاية دالة 

دالة نافذتي_حدث2
    اطبع("\n")
نهاية دالة

دالة رئيسية 

		نافذتي : ربط ( "MyButton1" ، نافذتي_حدث )
        نافذتي : ربط ( "MyButton2" ، نافذتي_حدث2 )
		نافذتي : إظهار ()
		اطبع ("Please wait 1 second.. \n")
		نم (1000)

		اطبع ("Please wait another one!.. \n")
		نم (1000)

		اطبع ("Run JavaScript.. \n")
		نص النتيجة = نافذتي : جافاسكريبت ( " document.getElementById(\"تجربة\").innerHTML = \"مرحبا من ألف !\"; " )

		نافذتي : إنتظار ()
نهاية دالة 
```
عند الضغط على الزر الأول عدة مرات لا تتم الطباعة حتى نضغط على الزر الثاني تتم طباعة كل ماسبق
سواء كتبنا "سطر" اول "\n"

**Comment by hassandraga** [comment]
<div dir="rtl">

المشكل هو أن WebUI ليس فيها "صف الإنتضام" حيث قد تتداخل الرسائل مع بعضها إذا كانت في وقت وجيز جدا
سأضيف هته الخاصية لاحقا
شكرا على التبليغ

**Comment by mohamedke** [comment]
الرسائل ليست في وقت وجيز،
قدد تتأخر الطباعة إلى نهاية البرنامج إذا لم توجد طباعة سطر جديد في البرنامج،
لو جاء أمر طباعة كتابة بدون سطر ثم قمت بالضغط على زر يقوم بعملية معينة، فإن تلك العملية تتم بدون أن يتم طباعة الكتابة،
لكن لو بعدها قمت بإيقاف البرنامج فإنها ستظهر الكتابة على شاشة الكونسول ثم يظهر اسم المستخدم الذي يدل على أن البرنامج إنتهى

**Comment by hassandraga** [comment]
<div dir=rtl>
أنا متأكد من أن هذه المشكلة مرتبطة بمكتبة WebUI وليس مترجم ألف.
شكرا على التبليغ
