### ISSUE TITLE
النداء على دوال نفس الصنف من داخله، مثل `this` أو `self` في بعض اللغات

### ISSUE THREAD

**Issue by assawalhy** [alifcommunity/compiler#32]
<div dir=rtl>

بالنسبة لي كنت أضعها في صنف لكن لم استطع إستدعاء الدوال التي بداخل الصنف عند محاولتي لكتابة الدوال ذات الأسماء المختصرة

```
صنف رياضيات

	-- طور الدالة الجيبية المسمى Pi
	خاص عدد ط
	-- الثابت الأسي e للدالة الأسية
	خاص عدد ه
	نص خطأ_رياضي

	دالة بناء()
		_س_ @ط@ = 3.14; _س_
		_س_ @ه@ = 2.7; _س_
	نهاية دالة

	دالة عدد جيب ( عدد أ)
		عدد حقيقي
		_س_
			@حقيقي@ = sin(@أ@);
		_س_
		إرجاع حقيقي
	نهاية دالة 

	دالة عدد جا( عدد أ )
		إرجاع جيب( أ )
	نهاية دالة

نهاية صنف
```

هذه رسالة الخطأ

```
 الملف		: C:\Alif3\examples\example.alif
 السطر		: 157

 الخطأ		: _TEST_TEST_TEST_' ( ' 
```

_Originally posted by @mohamedke in https://github.com/alifcommunity/compiler/issues/31#issuecomment-880171730_

**Comment by mohamedke** [comment]
شكرا على وضعه في خطأ مستقل

**Comment by mohamedke** [comment]
اقترح ان تكون هناك طريقتين للنداء إحداها التي ذكرت والأخرى نداء مباشر للدالة لأنها تنتمي لنفس المجال والصنف

**Comment by assawalhy** [comment]
<div dir=rtl>

ماذا لو كان في خارج الصنف دالة أو متغير بنفس الاسم وأريد استخدامه؟!

في الجافا، استخدام `this`  خياري، أي أنك يمكن أن تستخدمها أو استخدام المُعَرّافات بطريقة مباشرة.

**Comment by mohamedke** [comment]
يتم استخدام الشرطة السفلية للدوال والمتغيرات العامة،
_أ 
قبل اسم المتغير، وإن كان المتغير في مجال أعلى فسيتم النداء عليه من خلال اسم المجال
ليست جافا لوحدها، فأنا اخذت الفكرة من لغة Cpp

**Comment by hassandraga** [comment]
<div dir=rtl>
جاري الاصلاح، شكرا على التبليغ

**Comment by hassandraga** [comment]
<img width="498" alt="bug" src="https://user-images.githubusercontent.com/16948659/128114419-84e0c3c9-ba9c-46b0-9bb1-ddf309308218.png">

**Comment by hassandraga** [comment]
Fixed on v3.0.34
