### ISSUE TITLE
stop using prettier

### ISSUE THREAD

**Issue by hassandraga** [alifcommunity/compiler#43]
<div dir="rtl">
يبدو أن prettier لا يدعم C++ ، تنسيق الكود الذي قام به @MuhammadSawalhy  هو لجافا سكريبت وليس C++.

.
@MuhammadSawalhy 
هل تعرف أي منسق C++ جيد آخر يمكننا استخدامه جميعًا ?

https://github.com/prettier/prettier/issues/3683

**Comment by MuhammadSawalhy** [comment]
https://githu
b.com/alifcommunity/compiler/blob/db81bf7c18ee87be4f8e2304632455cc7d5d3e9c/.%D8%AE%D8%B7%D8%A7%D9%81%D8%A7%D8%AA_%D8%AC%D9%8A%D8%AA/pre-commit#L29

**Comment by assawalhy** [comment]
<div dir=rtl>

للمرة الثالثة أغلق issue بالخطأ 😅

---- 

المهم، تُستخدم **clang-format** مع الملفات `.c, .cc, .cpp, .h, .hpp`، وتستخدم **prettier** مع الملفات التي تصلح لها

</div>

https://github.com/alifcommunity/compiler/blob/db81bf7c18ee87be4f8e2304632455cc7d5d3e9c/.%D8%AE%D8%B7%D8%A7%D9%81%D8%A7%D8%AA_%D8%AC%D9%8A%D8%AA/pre-commit#L13-L14

https://github.com/alifcommunity/compiler/blob/db81bf7c18ee87be4f8e2304632455cc7d5d3e9c/.%D8%AE%D8%B7%D8%A7%D9%81%D8%A7%D8%AA_%D8%AC%D9%8A%D8%AA/pre-commit#L28-L38

**Comment by hassandraga** [comment]
<div dir="rtl">
من فضلك قم بتصحيح الشكل مرة تانية بستخدام prettier أو clang-format، فلقد غيرت الشكل في كل الملفات ولم تعد منضمة !

**Comment by assawalhy** [comment]
لتنسيق الملفات كلها:
```
clang-format -i **/*.{c,h,cc,cpp,hpp}
# يوجد قواعد مختلفة للتنسيق تُحدد من خلال الخيار --style
```

```
prettier -w **/*.{js,json,yaml,yml,html}
```

**Comment by assawalhy** [comment]
<div dir=rtl>

أظن أن هذه ال issue يمكن إغلاقها
