### ISSUE TITLE
حجم المشروع ضخم بسبب boost

### ISSUE THREAD

**Issue by assawalhy** [alifcommunity/compiler#5]
<div dir=rtl>

أرجو أن يتم الاستغناء عن ملفات الـ `thirdparty`، لأن حجمها ضخم ويستغرق الأمر وقتا طويلا أثناء `git clone`، كما أنه يفشل الأمر أحيانا ويتم المحاولة مرارا وتكرارا.

</div>

**Comment by hassandraga** [comment]
صحيح، أنا أعمل حاليا على نسخة `1.0.4` 
وهي ستأتي من دون مجلد 
`thirdparty`

**Comment by hassandraga** [comment]
لقد ثم حل هذا المشكل
لكن git history
فيه قائمة الملفات اللتي حذف.. 
يصل الحجم إلى 55 ميغا بسببه

علينا إجاد طريقة لمسح history

**Comment by hassandraga** [comment]
ثم حل مشكل 
history
أصبح حجم 
repo
فقط
2 mb

المرجو التأكد، ثم قفل هذا المشكل

**Comment by hassandraga** [comment]
بدأت تختلط عليا الأمور..
حللت المشكل في 
WebUI
سأحل نفس المشكل هنا غدا إن شاء الله

**Comment by assawalhy** [comment]
<div dir=rtl>

يمكنك أن تضع كل المشروع الحالي في فرع بدلا من ضياع تاريخ المشروع (ال commits السابقة)، وتبدأ فرع ال master من جديد بآخر نسخة موجودة من الأكواد.

**Comment by hassandraga** [comment]
لم أمسح ماستر، وإنما غيت هاب غيرو سياساتهم سنة 2020
غيرو ماستر إلى مين

**Comment by me00001** [comment]
<div dir=rtl> 

حلت المشكلة
شكرًا ! 

</div>

https://github.com/alifcommunity/compiler/commit/3f390406c3f7e018f1af968358bd57760c71fb7b
