### ISSUE TITLE
الترجمة تستمر بلا توقف 

### ISSUE THREAD

**Issue by me00001** [alifcommunity/compiler#7]
<div dir=rtl>

**أصدار : 3.0.17**

### العلة :
الشفرة لن تعمل وستسمر الترجمة مع زيادة في الرام بلا توقف
ودون الحصول على خطأ 

```
#ألف
دالة رئيسية 
 اطبع("! جدول الضرب ! \n")
 عدد الجدول=13
 عدد ب = 1
 كلما ب < الجدول
  عدد الناتج = ب * 12
  اطبع(ب + " * 12 = " + الناتج)
  اطبع("\n")
  ب = ب + 1
 نهاية كلما
نهاية دالة 
```

هذه الشفرة تعمل بلا مشاكل

```
#ألف
دالة رئيسية 
	اطبع("! جدول الضرب !")
	اطبع("\n")
	عدد الجدول=13
	عدد ب = 1
	كلما ب < الجدول
		عدد الناتج = ب * 12
		اطبع(ب + " * 12 = " + الناتج)
		اطبع("\n")
		ب = ب + 1
	نهاية كلما
نهاية دالة 
```

### وصف المشكلة : 
تبدأ المشكلة عند اضافة سطر جديد بأستخدام \n تحدث في بعض الأحيان ولا أعرف السبب 
</div>

**Comment by hassandraga** [comment]
لاحضت هذا الأمر في فيديو لأستادة تشرح لغة ألف للطلاب
ولم أعرف الشيفرة اللتي تتسبب في هذا
أنت أول شخص يجد الشيفرة
سأبحث عن حل اليوم وأصلحه
أشكرك كثيرا على التبليغ

**Comment by assawalhy** [comment]
<div dir=rtl>

أظن أن المشكلة حلت في `v3.0.20 (Beta)`

**Comment by hassandraga** [comment]
<div dir=rtl>
جربته للتو على ويندوز ويبدو أنه يعمل

**Comment by me00001** [comment]
ممتاز مته ماتكررت المشكلة يمكن اعادة فتحها

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا على التبليغ

ثم إصلاح العلة في النسخة 3.0.22
