### ISSUE TITLE
Linking libraries error: in example `./webui.alif`

### ISSUE THREAD

**Issue by assawalhy** [alifcommunity/compiler#8]
<div dir=rtl>

هذا ما يحدث عندما أنفذ مثال الـ webui:

<div dir=ltr>

```bash
❯ alif --input ./webui.alif
```

</div>

[![asciicast](https://asciinema.org/a/G7yiLRNigdegpiUDimHmglzwl.svg)](https://asciinema.org/a/G7yiLRNigdegpiUDimHmglzwl)

هذا هو محتوى `./webui.alif.log`:

<div dir=ltr>

```
 143   │ 
 144   │ FINAL_APPLICATION_CODE_CHECKING()... 
 145   │ 
 146   │  ----------- DEBUGING FINISH ------------- 
 147   │ Please report this error to the Alif Community: https://github.com/alifcommunity/compiler/issues 
 148   │ Alif Compiler 3.0.17 (Beta) - Linux
 149   │ 
 150   │ File : ./webui.alif
 151   │ Error: Linking Librarys error.
```

</div>

</div>

**Comment by hassandraga** [comment]
<div dir=rtl>

يبدو أن linker لم يجد مكتبة ما
من فضلك أرسل نص الطرفية
أحتاج معرفة أي reference لم يجد

</div>

**Comment by hassandraga** [comment]
أقصد
undefined references...

**Comment by mohamedke** [comment]
<div dir=rtl>
يظهر لي نفس الخطأ أظنه لم يجد مكتبة libboostfilesystem 

هذا بعض نص الخطأ
</div>

```

/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.unlikely+0x1ba): undefined reference to `__imp_TlsGetValue'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.unlikely+0x22e): undefined reference to `__imp_TlsGetValue'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.unlikely+0x2a2): undefined reference to `__imp_TlsGetValue'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.unlikely+0x316): undefined reference to `__imp_TlsGetValue'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.startup+0x23): undefined reference to `operator new(unsigned long long)'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.startup+0x66): undefined reference to `__imp_GetLastError'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.startup+0x31e): undefined reference to `__imp_TlsAlloc'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.startup+0x437): undefined reference to `__imp_TlsAlloc'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text.startup+0x47e): undefined reference to `__imp_TlsAlloc'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x28c): undefined reference to `__imp_TlsFree'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x2ac): undefined reference to `__imp_TlsFree'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x2cc): undefined reference to `__imp_TlsFree'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x373): undefined reference to `__imp_WSAStartup'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x3bc): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x3f6): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x418): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x476): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x49a): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x576): more undefined references to `__imp__assert' follow
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x637): undefined reference to `__imp_EnterCriticalSection'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x66c): undefined reference to `__imp_LeaveCriticalSection'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x766): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0x7c4): undefined reference to `operator new(unsigned long long)'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0xa51): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0xc6a): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0xc8a): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0xcaa): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0xcd0): undefined reference to `__imp__assert'
/usr/bin/ld: /usr/local/lib/aliflib/libwebui.a(webui.cpp.obj):webui.cpp:(.text+0xd4e): more undefined references to `__imp__assert' follow

```

**Comment by hassandraga** [comment]
Did you build the _WebUI_ from source on your machine ?

**Comment by assawalhy** [comment]
[webui-stderr.log](https://github.com/alifcommunity/compiler/files/6162100/webui-stderr.log)

**Comment by waseeld** [comment]
انا ايضا وقعت في نفس المشكلة أعتقد أن مكتبة
 `Webui` هي السبب
هل يتوجب علي بناء المكتبة من المصدر قبل مترجم ألف ؟؟ مع العلم اني قمت بذلك قبل حوالي 3 اشهر

**Comment by hassandraga** [comment]
فهمت
مترجم ألف لا يضيف كل المكتبات الازمة
سأضيف ماكرو ألف يخبر مترجم ألف بالمكتبات الازمة
مثلا

#أضف_في_ترجمة "-mbig-obj"
#أضف_في_التجميع "-lboost_filesystem -lwebsocket"

**Comment by hassandraga** [comment]
هذا يعني، مثلا نضيف هته السطور في ملف
واجهة.alif
لحل كل مشاكل
undefined references

ما رأيكم؟

**Comment by waseeld** [comment]
@hassandraga انا اراها فكرة رائعة

**Comment by mohamedke** [comment]
<div dir=rtl>

> فهمت
> مترجم ألف لا يضيف كل المكتبات الازمة
> سأضيف ماكرو ألف يخبر مترجم ألف بالمكتبات الازمة
> مثلا
> 
> #أضف_في_ترجمة <span dir=ltr>"-mbig-obj"</span>
> #أضف_في_التجميع <span dir=ltr>"-lboost_filesystem -lwebsocket"</span>

كنت سأقترح هذه الفكرة فيما بعد لكن ليس بهذه الطريقة،
نجعلها في ألف استوديو مثلما هي باقي ide

**Comment by mohamedke** [comment]
<div dir=rtl>

ليس الخلل هنا؟ المترجم يستعملها لكن لا ادري ما السبب، لأنه يظهر في الأخير أن المترجم استدعى مكتبة libboost_filesystem
تجد الأمر مكتبوب بهذا الشكل

<div dir=ltr>

    g++ ........ -lwebui -lboost_filesystem

</div>

سأرسل فيما بعد النص كاملا لأنني حاليا اشتغل على الوندوز

**Comment by mohamedke** [comment]
بعد أن قمت بتوجيه الأخطاء إلى ملف ظهرت الأخطاء نفسها التي ظهرت مع الأخ مصطفى في الملف، وباقي النتائج ظهرت على الترمنال لأنها ليست أخطاء
./../build/Alif/alif webui.alif 2> error.log

Debuging: g++ -Os -static-libgcc -static-libstdc++ -m64 -finput-charset=utf-8 -pthread -o "/home/mohamed/Desktop/compiler-master/examples/webui" "/tmp/alifcompiler_0000.o" -L"/usr/local/lib/aliflib" -lwebui -lboost_filesystem

Please report this error to the Alif Community: https://github.com/alifcommunity/compiler/issues 
Alif Compiler 3.0.17 (Beta) - Linux

File : /home/mohamed/Desktop/compiler-master/examples/webui.alif
Error: Linking Librarys error.
كما هو ظاهر لغة ألف تستدعي مكتبة libboost_filesystem عند محاولة الترجمة

**Comment by hassandraga** [comment]
ألف حاليا يضيف مكتبة
WebUI و كذالك boost
حتى لو لم تستعمل

لدى النسخة القادمة ستضاف فقط عند الحاجة
سواء عن طريق ماكرو أو عن طريق سطر الأوامر

**Comment by hassandraga** [comment]
عن طريق الماكرو

#أضف_في_ترجمة "-mbig-obj"
#أضف_في_التجميع "-lboost_filesystem -lwebsocket"

عن طريق سطر الأوامر

alif test.alif --o test.exe --clib webui --clib boost_filesystem

**Comment by mohamedke** [comment]
> ألف حاليا يضيف مكتبة
> WebUI و كذالك boost
> حتى لو لم تستعمل
> 
> لدى النسخة القادمة ستضاف فقط عند الحاجة
> سواء عن طريق ماكرو أو عن طريق سطر الأوامر

هل يتم استدعاء مكتبة بوست في برامج سطر الأوامر، إذا كان الجواب نعم فلا حاجة لإزالتها لأن البرنامج يشتغل بشكل عادي ولا يكون فيه مشكل الربط

**Comment by mohamedke** [comment]
> عن طريق الماكرو
> 
> #أضف_في_ترجمة "-mbig-obj"
> #أضف_في_التجميع "-lboost_filesystem -lwebsocket"
> 
> عن طريق سطر الأوامر
> 
> alif test.alif --o test.exe --clib webui --clib boost_filesystem

ماذا لو جعلناها من خيارات ألف استوديو وليس عن طريق الماكرو؟

**Comment by assawalhy** [comment]
<div dir=rtl>

> ماذا لو جعلناها من خيارات ألف استوديو وليس عن طريق الماكرو؟

ماذا لو استطعنا عمل إضافات لمحررات الأكواد الحالية مثل VS code؟ أليس من الأفضل أن يكون ذلك من خلال سطر الأوامر أو داخل كود ألف نفسه؟ هذا سيفتح الطريق أما إمكانات أكبر. وسيعطي مستخدم لغة ألف مرونة.

**Comment by mohamedke** [comment]
> > ماذا لو جعلناها من خيارات ألف استوديو وليس عن طريق الماكرو؟
> 
> ماذا لو استطعنا عمل إضافات لمحررات الأكواد الحالية مثل VS code؟ أليس من الأفضل أن يكون ذلك من خلال سطر الأوامر أو داخل كود ألف نفسه؟ هذا سيفتح الطريق أما إمكانات أكبر. وسيعطي مستخدم لغة ألف مرونة.

فهمتك، فكرة جيدة

**Comment by me00001** [comment]
<div dir=rtl>

> > ماذا لو جعلناها من خيارات ألف استوديو وليس عن طريق الماكرو؟
> 
> ماذا لو استطعنا عمل إضافات لمحررات الأكواد الحالية مثل VS code؟ أليس من الأفضل أن يكون ذلك من خلال سطر الأوامر أو داخل كود ألف نفسه؟ هذا سيفتح الطريق أما إمكانات أكبر. وسيعطي مستخدم لغة ألف مرونة.


هذا لأن VS Code لايدعم اللغات المكتوبة من اليمين لليسار
أنظر بعض المحاولات 

</div>

https://github.com/microsoft/vscode/issues/11770

**Comment by assawalhy** [comment]
أعلم هذا، يمكن لبيئة تطوير ألف أن تستعمل سطر الأوامر، وكذلك لو استطعنا عمل إضافات للمحررات الحالية، ونعطي المبرمجين بألف المرونة لإستخدامها كما يشاءون.

**Comment by me00001** [comment]
<dev dir="rtl">
هل توجد في ألف 3.0.20 ؟
</dev>

**Comment by assawalhy** [comment]
لا تزال موجودة للأسف

**Comment by hassandraga** [comment]
<div dir="rtl">
شكرا على التبليغ

سيتم إضافة هته الميزة في النسخة القادمة إن شاء الله

**Comment by hassandraga** [comment]
<div dir="rtl">
ثم الحل نسخة 3.0.30

**Comment by assawalhy** [comment]
<div dir=rtl>

فعلا نجحت الترجمة، لكن عند محاولة التشغيل هذا ما يحدث، ولا تظهر أي نوافذ

![image](https://user-images.githubusercontent.com/42011920/123605629-927ec500-d7eb-11eb-96d2-d2f2d73b509c.png)

**Comment by hassandraga** [comment]
<div dir="rtl">
جاري البحث والإصلاح

**Comment by me00001** [comment]
<div dir="rtl">

> فعلا نجحت الترجمة، لكن عند محاولة التشغيل هذا ما يحدث، ولا تظهر أي نوافذ
> 
> ![image](https://user-images.githubusercontent.com/42011920/123605629-927ec500-d7eb-11eb-96d2-d2f2d73b509c.png)

**هذا خطأ أخر سأفتح موضوع جديد به#29 أما خطأ هذا الموضوع #8 تم اصلاحه** 
![لقطة شاشة من 2021-07-01 10-19-18](https://user-images.githubusercontent.com/37930867/124083286-5b601c00-da56-11eb-86d4-93d1d3168bd5.png)
