### ISSUE TITLE
finding file

### ISSUE THREAD

**Issue by mohamedke** [alifcommunity/compiler#9]
<div dir=auto>

عندما نشغل ألف من الطرفية البرنامج يبحث عن الملفات في المجلد الحالي للطرفية ولايبحث في مجلد المشروع كمثال:
محتوى الملف webui.alif
#نص "win.htlm"

عندما نشغل الطرفية من نفس مجلد المشروع فإنه سيبحث عن هذا المجلد 
alif webui.alif

لكن بافتراض اننا شغلنا الف في الطرفية من مجلد آخر سيبحث عن ملف win.html في نفس مجلد الطرفية
ولا يبحث عنه في المجلد الموجود فيه ملف webui.alif
كمثال
alif ./example/webui.alif
سيبحث هكذا ./win.html
ولا يبحث عنه بهذه الطريقة ./example/win.html

**Comment by mohamedke** [comment]
الخطأ هو

 الملف		: ./examples/webui.alif
 السطر		: 5

 الخطأ		: ملف غير موجود : ' "win.html" '

**Comment by hassandraga** [comment]
صحيح، سأضيف خاصية 
--debug
بحيث نرى ما يفعله المترجم بالظبط
هذا سيساعدنا على فهم سبب المشكل وإصلاحه

**Comment by hassandraga** [comment]
<div dir="rtl">
جربته للتو على ويندوز ويبدو أنه يعمل

سأجربه على اللينكس لأتيقن

<div dir="ltr">


```
C:\folder1>alif C:\Alif3\examples\webui.alif
C:\folder1>
```

**Comment by hassandraga** [comment]
<div dir="rtl">
ثم التصحيح في نسخة 3.0.21، المرجو المراجعة والتدقيق

شكرا على التبليغ

**Comment by hassandraga** [comment]
<div dir="rtl">
أخ محمد، هل يعمل الحل اللذي أضفنا في النسخة الأخيرة ؟

**Comment by mohamedke** [comment]
للأسف فإن الترجمة لم تنجح بعد لكي أعرف هل تم إصلاح المشكل أم لا على لينكس، يظهر لي خطأ في الربط
انظر هنا: #27

**Comment by hassandraga** [comment]
<div dir="rtl">
ثم الحل نسخة 3.0.30

**Comment by hassandraga** [comment]
ثم الحل ?

**Comment by mohamedke** [comment]
نعم تم الحل، كل الشكر لك وللفريق القائم عليها.
